server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
        
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5150/user

spring:
  application:
    name: 'flashcards-server'
  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: admin
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update #drop n create table again, good for testing, comment this in production    
